######################################################################
#
# File name : ALU_Random_simulate.do
# Created on: Mon Mar 10 00:13:40 -0400 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.ALU_Random xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {ALU_Random_wave.do}

view wave
view structure
view signals

do {ALU_Random.udo}

run 1000ns
