######################################################################
#
# File name : ALU_Random_wave.do
# Created on: Mon Mar 10 00:13:40 -0400 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
