######################################################################
#
# File name : ALU_Random_compile.do
# Created on: Mon Mar 10 00:13:35 -0400 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../ALU.srcs/sources_1/new/ALU_Random.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

