######################################################################
#
# File name : tb_ALU_Random_simulate.do
# Created on: Thu Mar 13 02:29:52 -0400 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_ALU_Random xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_ALU_Random_wave.do}

view wave
view structure
view signals

do {tb_ALU_Random.udo}

run 1000ns
