######################################################################
#
# File name : tb_ALU_Random_wave.do
# Created on: Thu Mar 13 02:28:55 -0400 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
